"""
Module Name: foc_motor_simulator.py
Description: Mathematical simulation of a Permanent Magnet Synchronous Motor (PMSM)
             utilizing Field-Oriented Control (FOC) vector transformations.
Target Focus: System-level modeling, control loop verification, and algorithmic validation.
"""

import numpy as np

class PMSMMotorSimulator:
    def __init__(self):
        # --------------------------------------------------------------------------
        # Physical Motor Parameters (Typical EV Traction Motor Specifications)
        # --------------------------------------------------------------------------
        self.Rs = 0.05        # Stator Resistance (Ohms)
        self.Ld = 0.0002      # d-axis Inductance (Henries)
        self.Lq = 0.0002      # q-axis Inductance (Henries)
        self.psi_f = 0.05     # Permanent Magnet Flux Linkage (Weber)
        self.P = 4            # Number of Pole Pairs
        self.J = 0.01         # Rotor Inertia (kg*m^2)
        self.B = 0.001        # Viscous Friction Coefficient

        # Internal State Variables
        self.id = 0.0         # d-axis current (Magnetizing current component)
        self.iq = 0.0         # q-axis current (Torque-producing current component)
        self.omega_m = 0.0    # Mechanical rotor speed (rad/s)
        self.theta_e = 0.0    # Electrical rotor position (rad)

    def clarke_transform(self, ia, ib, ic):
        """
        Transforms 3-phase stationary currents (ia, ib, ic) into 2-phase 
        orthogonal stationary coordinates (alpha, beta).
        Uses the power-invariant variant.
        """
        i_alpha = ia
        i_beta = (1.0 / np.sqrt(3.0)) * ia + (2.0 / np.sqrt(3.0)) * ib
        return i_alpha, i_beta

    def park_transform(self, i_alpha, i_beta, theta_e):
        """
        Transforms 2-phase stationary coordinates (alpha, beta) into 
        rotating reference frame coordinates (d, q) based on electrical angle.
        """
        cos_t = np.cos(theta_e)
        sin_t = np.sin(theta_e)
        id_frame =  i_alpha * cos_t + i_beta * sin_t
        iq_frame = -i_alpha * sin_t + i_beta * cos_t
        return id_frame, iq_frame

    def inverse_park_transform(self, vd, vq, theta_e):
        """
        Transforms rotating d-q voltage references back into stationary 
        orthogonal alpha-beta reference vectors for the hardware PWM block.
        """
        cos_t = np.cos(theta_e)
        sin_t = np.sin(theta_e)
        v_alpha = vd * cos_t - vq * sin_t
        v_beta  = vd * sin_t + vq * cos_t
        return v_alpha, v_beta

    def update_physics(self, vd, vq, load_torque, dt):
        """
        Solves the continuous-time state-space differential equations of the PMSM
        using basic numerical integration (Euler's Method).
        """
        # Electrical frequency tracking
        omega_e = self.omega_m * self.P
        
        # 1. Compute derivative of d-q currents based on motor dynamics equations
        did_dt = (vd - self.Rs * self.id + omega_e * self.Lq * self.iq) / self.Ld
        diq_dt = (vq - self.Rs * self.iq - omega_e * self.Ld * self.id - omega_e * self.psi_f) / self.Lq
        
        # 2. Integrate to find new current vector matrix values
        self.id += did_dt * dt
        self.iq += diq_dt * dt
        
        # 3. Compute electromagnetic torque generated by the motor
        # Te = 1.5 * P * [psi_f * iq + (Ld - Lq) * id * iq]. Since Ld=Lq (Non-salient), second term drops out.
        t_electromagnetic = 1.5 * self.P * self.psi_f * self.iq
        
        # 4. Compute mechanical acceleration update
        domega_dt = (t_electromagnetic - load_torque - self.B * self.omega_m) / self.J
        self.omega_m += domega_dt * dt
        
        # 5. Advance electrical angle orientation matrix
        self.theta_e += omega_e * dt
        # Normalize angle wrap-around between 0 and 2*pi
        self.theta_e = self.theta_e % (2 * np.pi)
        
        return self.omega_m, t_electromagnetic

# --------------------------------------------------------------------------
# Execution Script: Test Execution Loop replicating an ECU Control Cycle
# --------------------------------------------------------------------------
if __name__ == "__main__":
    motor = PMSMMotorSimulator()
    time_step = 0.0001  # 100 microsecond control calculation cycle (10kHz frequency)
    total_steps = 1000  # Running simulation window
    
    print("Initializing FOC Physical Loop Verification...")
    print(f"{'Time(s)':<10}{'Target Vq':<12}{'I_d (A)':<10}{'I_q (A)':<10}{'Speed (rad/s)':<15}")
    print("-" * 60)
    
    for step in range(total_steps):
        current_time = step * time_step
        
        # Emulate active throttle input injecting 12V into torque-producing q-axis
        test_vq_input = 12.0 if current_time > 0.01 else 0.0
        test_vd_input = 0.0  # Maintain zero d-axis current for maximum torque per ampere (MTPA)
        
        # System update step calculation
        speed, torque = motor.update_physics(test_vd_input, test_vq_input, load_torque=0.5, dt=time_step)
        
        # Print metrics at defined periodic sub-intervals
        if step % 200 == 0:
            print(f"{current_time:<10.4f}{test_vq_input:<12.2f}{motor.id:<10.3f}{motor.iq:<10.3f}{speed:<15.3f}")
            
    print("-" * 60)
    print("Simulation execution complete. Control algorithms verified mathematically.")
